<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/eThangAgent.Agent.Infrastructure/eThangAgent.Agent.Infrastructure.csproj" />
    <ProjectReference Include="../../src/eThangAgent.Agent.Domain/eThangAgent.Agent.Domain.csproj" />
    <ProjectReference Include="../../src/eThangAgent.SharedKernel/eThangAgent.SharedKernel.csproj" />
  </ItemGroup>
</Project>
