<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1515;CA2007;CA1849;S6966</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../eThangAgent.Transport.ACL/eThangAgent.Transport.ACL.csproj" />
    <ProjectReference Include="../eThangAgent.Agent.Infrastructure/eThangAgent.Agent.Infrastructure.csproj" />
    <ProjectReference Include="../eThangAgent.Storage.ACL/eThangAgent.Storage.ACL.csproj" />
    <ProjectReference Include="../eThangAgent.Composition/eThangAgent.Composition.csproj" />
  </ItemGroup>
</Project>